language: python
python:
    - "3.3"
    - "3.4"
install:
    - pip install .
    - pip install nose coverage
script:
    - nosetests --with-coverage --cover-package=greyskull
    - coverage report -m
after_success:
    - pip install coveralls
    - coveralls
